v03.00017 Fixes #2867 pt1
* inputbindings shovel position

added input bindings for shovelpositions, but still get an error when using it:
Error: Running LUA method 'update'.
D:/user_andyk/Dokumente/My Games/FarmingSimulator2017/mods/FS17_CoursePlay5/mode9.lua:358: attempt to get length of local 'movingTools' (a nil value)

* beautyfied

ein paar kleine Schönheitskorrekturen am Code

* changed: no more waiting until key positioning has finished until you can set a new position.

* fixed missing nil handling